---
- hosts: all
  tasks:
  - name: Common variables
    include_vars: vars/common.yml

  - name: Local variables
    include_vars: "{{ item }}"
    with_first_found:
      - "vars/local_layout_{{app_layout}}.yml"
      - "vars/{{ansible_os_family|lower}}.yml"
      - "vars/defaults.yml"

- hosts: all
  tasks:
  - name: Selected layout
    debug:
      msg: "echo {{app_layout}}"

  - name: Selected tracker release
    debug:
      msg: "echo {{tracker_release}}"

  - name: Selected target directory
    debug:
      msg: "echo {{webapp_directory}}"
