---
- hosts: all
  roles:
  roles:
    # - { role: database, tags: [ 'database' ], when: install_database }
    # - { role: java, tags: [ 'java' ], when: install_java }
    - { role: webapp, tags: [ 'webapp' ] }
