---
- name: Local variables
  include_vars: "{{ item }}"
  with_first_found:
    - "vars/local_layout_{{app_layout}}.yml"
    - "vars/{{ansible_os_family|lower}}.yml"
    - "vars/defaults.yml"

- name: Standalone | Create directories
  shell: mkdir -p {{ item.path }} creates={{ item.path }}
  with_items:
    - { path: '{{webapp_log_directory}}' }
    - { path: '{{webapp_pid_directory}}' }

- name: Standalone | Write configuration files
  template: src={{ item.src }} dest={{ item.dest }} mode={{ item.mode }}
  notify:
    - restart service
  with_items:
    - { src: "tracker.xml.j2", dest: "{{webapp_service_config}}/tracker.xml", mode: '0644' }
    - { src: "init.d.j2", dest: "{{webapp_service_config}}/init.d", mode: '0644' }
