---
- name: Local variables
  include_vars: "{{ item }}"
  with_first_found:
    - "vars/local_layout_{{app_layout}}.yml"
    - "vars/{{ansible_os_family|lower}}.yml"
    - "vars/defaults.yml"

- name: Webapp | Create directories
  shell: mkdir -p {{ item.path }} creates={{ item.path }}
  with_items:
    - { path: '{{webapp_directory}}' }
    - { path: '{{webapp_log_directory}}' }
    - { path: '{{webapp_pid_directory}}' }
    - { path: '{{webapp_service_config}}' }

- name: Webapp | Get release files
  get_url:
    url: "{{item.url}}"
    dest: "{{item.dest}}"
  with_items:
    - { url: "{{tracker_release}}", dest: "{{webapp_directory}}/tracker-{{tracker_version}}.jar" }
    - { url: "{{tracker_server_release}}", dest: "{{webapp_directory}}/tracker-server-{{tracker_version}}.jar" }

- name: Webapp | Get database schema
  get_url:
    url: "{{item.url}}"
    dest: "{{item.dest}}"
  with_items:
    - { url: "{{tracker_release_base}}/initialize_mysql.sql", dest: "{{webapp_directory}}/initialize_mysql.sql" }

## TODO Webapp | Update the database

- name: Webapp | Write configuration files
  template: src={{ item.src }} dest={{ item.dest }} mode={{ item.mode }}
  notify:
    - restart service
  with_items:
    - { src: "tracker.xml.j2", dest: "{{webapp_service_config}}", mode: '0644' }
    - { src: "init.d.j2", dest: "{{webapp_service_config}}", mode: '0644' }

- name: Webapp | Create user
  user:
    name: "{{webapp_service_user}}"
    comment: "{{webapp_service_user}} webapp"
    state: present
  when: install_user == true

- name: Webapp | Assign files to the user
  file:
    path: "{{ item.path }}"
    recurse: yes
    owner: "{{webapp_service_user}}"
    group: adm
    mode: "{{ item.mode }}"
  with_items:
    - { path: '{{webapp_log_directory}}', mode: '0750' }
    - { path: '{{webapp_pid_directory}}', mode: '0750' }
    - { path: '{{webapp_directory}}', mode: '0755' }
  when: install_user == true

- name: Webapp | ensure the service is running
  service:
    name: "{{webapp_service_name}}"
    state: started
    enabled: yes
  when: install_service == true
