---
- name: Local variables
  include_vars: "{{ item }}"
  with_first_found:
    - "vars/local_layout_{{app_layout}}.yml"
    - "vars/{{ansible_os_family|lower}}.yml"
    - "vars/defaults.yml"

- name: Webapp | Create directories
  shell: mkdir -p {{ item.path }} creates={{ item.path }}
  with_items:
    - { path: '{{webapp_directory}}' }

- name: Webapp | Get release files
  get_url:
    url: "{{item.url}}"
    dest: "{{item.dest}}"
  with_items:
    - { url: "{{tracker_release}}", dest: "{{webapp_directory}}/tracker-java-restlet-{{tracker_version}}.war" }

## Only read the service container when we're installing the service

- name: Webapp | Get release files
  get_url:
    url: "{{item.url}}"
    dest: "{{item.dest}}"
  when: install_service or deploy_standalone
  with_items:
    - { url: "{{tracker_server_release}}", dest: "{{webapp_directory}}/tracker-server-{{tracker_server_version}}.jar" }

- name: Webapp | Get database schema
  get_url:
    url: "{{item.url}}"
    dest: "{{item.dest}}"
  with_items:
    - { url: "{{tracker_release_base}}/initialize_mysql.sql", dest: "{{webapp_directory}}/initialize_mysql.sql" }

## TODO Webapp | Update the database
