---
- name: Webapp | Create directories
  shell: mkdir -p {{ item.path }} creates={{ item.path }}
  with_items:
    - { path: '{{webapp_directory}}' }
    - { path: '{{webapp_log_directory}}' }
    - { path: '{{webapp_pid_directory}}' }
    - { path: '{{webapp_directory}}/data' }

- name: Webapp | Get release files
  get_url:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
  with_items:
    - { src: "{{tracker_release}}", dest: "{{webapp_directory}}/tracker-{{tracker_version}}.jar" }
    - { src: "{{tracker_server_release}}", dest: "{{webapp_directory}}/tracker-server-{{tracker_version}}.jar" }

## TODO Webapp | Get database schema

## TODO Webapp | Update the database

- name: Webapp | Write configuration files
  template: src={{ item.src }} dest={{ item.dest }} mode={{ item.mode }}
  notify:
    - restart service
  with_items:
    - { src: "webapp.config.j2", dest: "{{webapp_service_config}}", mode: '0644' }
    - { src: "webapp.init.j2", dest: "{{webapp_service_init}}", mode: '0755' }

- name: Webapp | Create user
  user:
    name: "{{webapp_service_user}}"
    comment: "{{webapp_service_user}} webapp"
    state: present

- name: Webapp | Assign files to the user
  file:
    path: "{{ item.path }}"
    recurse: yes
    owner: "{{webapp_service_user}}"
    group: adm
    mode: "{{ item.mode }}"
  with_items:
    - { path: '{{webapp_log_directory}}', mode: '0750' }
    - { path: '{{webapp_pid_directory}}', mode: '0750' }
    - { path: '{{webapp_directory}}', mode: '0755' }
    - { path: '{{webapp_directory}}/data', mode: '0777' }

- name: Webapp | ensure the service is running
  service:
    name: "{{webapp_service_name}}"
    state: started
    enabled: yes
