---
- name: Local variables
  include_vars: "{{ item }}"
  with_first_found:
    - "../../../vars/local_layout_{{app_layout}}.yml"
    - "../../../vars/{{ansible_os_family|lower}}.yml"
    - "../../../vars/defaults.yml"

- name: Webapp | Create directories
  shell: mkdir -p {{ item.path }} creates={{ item.path }}
  with_items:
    - { path: '{{webapp_directory}}' }

- name: Webapp | Get release files
  get_url:
    url: "{{item.url}}"
    dest: "{{item.dest}}"
    sha256sum: "{{item.sha256sum}}"
  with_items:
    - { url: "{{tracker_release}}", dest: "{{webapp_directory}}/tracker-webapp-{{tracker_version}}.war", sha256sum: "{{tracker_release_checksum}}" }

## Only read the service container when we're installing the service

- name: Webapp | Get release files
  get_url:
    url: "{{item.url}}"
    dest: "{{item.dest}}"
    sha256sum: "{{item.sha256sum}}"
  when: install_service or deploy_standalone
  with_items:

- name: Webapp | Get database schema
  get_url:
    url: "{{item.url}}"
    dest: "{{item.dest}}"
    sha256sum: "{{item.sha256sum}}"
  with_items:
    - { url: "{{tracker_release_database}}", dest: "{{webapp_directory}}/initialize_mysql.sql", sha256sum: "{{tracker_release_database_checksum}}" }
    - { url: "{{java_server_release}}", dest: "{{webapp_directory}}/java-server-{{java_server_version}}.jar", sha256sum: "{{java_server_release_checksum}}" }

- name: Webapp | Create properties file
  file:
    path: "{{webapp_directory}}/tracker.properties"
    state: 'touch'
    mode: '0644'


## TODO Webapp | Update the database
