---

- name: Java | Install OpenJDK runtime
  apt:
    pkg: openjdk-8-jre-headless
    state: present
    update_cache: yes
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"

- name: Java | Install OpenJDK runtime
  yum:
    name: java-1.8.0-openjdk-headless.x86_64
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Java | Set default Java
  shell: update-java-alternatives --set java-1.8.0-openjdk-amd64
  when: ansible_os_family == "Debian"

# TODO select using alternatives on CentOS
