---
- name: Local variables
  include_vars: "{{ item }}"
  with_first_found:
    - "vars/local_layout_{{app_layout}}.yml"
    - "vars/{{ansible_os_family|lower}}.yml"
    - "vars/defaults.yml"

- name: Service | Create directories
  shell: mkdir -p {{ item.path }} creates={{ item.path }}
  with_items:
    - { path: '{{webapp_directory}}' }
    - { path: '{{webapp_log_directory}}' }
    - { path: '{{webapp_pid_directory}}' }
    - { path: '{{webapp_service_config}}' }

- name: Service | Write configuration files
  template: src={{ item.src }} dest={{ item.dest }} mode={{ item.mode }}
  notify:
    - restart service
  with_items:
    - { src: "tracker.xml.j2", dest: "{{webapp_service_config}}/tracker.xml", mode: '0644' }
    - { src: "init.d.j2", dest: "{{webapp_service_config}}/init.d", mode: '0644' }

- name: Service | Create user
  user:
    name: "{{webapp_service_user}}"
    comment: "{{webapp_service_user}} webapp"
    state: present
  when: install_user == true && install_service == true

- name: Service | Assign files to the user
  file:
    path: "{{ item.path }}"
    recurse: yes
    owner: "{{webapp_service_user}}"
    group: adm
    mode: "{{ item.mode }}"
  with_items:
    - { path: '{{webapp_log_directory}}', mode: '0750' }
    - { path: '{{webapp_pid_directory}}', mode: '0750' }
    - { path: '{{webapp_directory}}', mode: '0755' }
  when: install_user == true

- name: Service | ensure the service is running
  service:
    name: "{{webapp_service_name}}"
    state: started
    enabled: yes
  when: install_service == true
